import type { Metadata } from "next";
import { Liu_Jian_Mao_Cao, Poppins } from "next/font/google";
import "./globals.css";
import * as THREE from "three";

const maoCao = Liu_Jian_Mao_Cao({
  variable: "--font-liu-jian-mao-cao",
  weight: ["400"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Cai Shen Ye",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${maoCao.variable} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
